version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-browsers

    steps:
      - checkout

      - run:
          command: ls && pwd

      - run:
          command: sudo apt-get install pylint mysql-client python-mysqldb && sudo pip install -r requirements.txt
